Feature/ockovanienh
msusicky/ockovani-covid pull request #268
Opened 2021-03-23 21:47 UTC by msusicky

Added environment variable ODL_VACCINATED_ENH
If filled then this path will be used as a source for the enhanced vaccination data

2021-03-27 18:51 UTC, jan-stanek commented on app/opendata_fetcher.py
> +            if os.environ.get('ODL_VACCINATED_ENH') is not None and os.path.exists(
os.environ.get('ODL_VACCINATED_ENH') can be stored to some variable

2021-03-27 18:53 UTC, jan-stanek commented on app/opendata_fetcher.py
> +                kraj_nuts_kod=row[2],
names of columns are more readable then numbers

2021-03-27 18:55 UTC, jan-stanek commented on app/opendata_fetcher.py
> +                zarizeni_kod=format(int(row[3]), '011d'),
this can cause issues, some codes are higher than INT_MAX

2021-03-27 19:06 UTC, jan-stanek commented on app/opendata_fetcher.py
> +                zarizeni_kod=format(int(row[3]), '011d'),
we read all columns as strings, so it shouldn't be needed

2021-03-27 19:08 UTC, jan-stanek requested changes
see comments

2021-03-29 20:29 UTC, msusicky commented
See changes :)

2021-03-29 20:39 UTC, jan-stanek requested changes

2021-03-29 20:39 UTC, jan-stanek commented on app/opendata_fetcher.py
> +            OpenDataFetcher._vaccinated_profese = os.environ.get('ODL_VACCINATED_ENH')
self

2021-03-29 20:39 UTC, jan-stanek commented on app/opendata_fetcher.py
> +                self._fetch_vaccinated_profese_path(self._vaccinated_profese)
vaccinated_professions would be better :)

2021-03-30 18:29 UTC, jan-stanek approved these changes

2021-03-30 18:30 UTC, merged